id = "mcp-server-github"
name = "GitHub MCP Server"
description = "Model Context Protocol Server for GitHub"
version = "0.0.4"
schema_version = 1
authors = [
  "Jeffrey Guenther <guenther.jeffrey@gmail.com>",
  "James Inman <james@jamesinman.co.uk>",
]
repository = "https://github.com/LoamStudios/zed-mcp-server-github"

[context_servers.mcp-server-github]
name = "GitHub MCP Server"
